### PR TITLE
Removes build warnings

### PR DESCRIPTION
**Pull request by yudistrange**
The plugin in itself is compatible with the latest JOSM version. However there are deprecation warnings and one of the classes being used in the plugin will be removed at the end of 2017.

- The changes remove deprecated code usage
- Fixes import statements

### CODE REVIEW

**Comment by batpad** [comment]
cc @geohacker - this looks good to me - should we hit merge or anything else to think about?

Thanks much @yudistrange !

**Comment by geohacker** [comment]
@yudistrange - thank you! 
@batpad - this is 👍 from me, let's merge!

**Comment by Rub21** [comment]
This looks good to me!!  i will merge!!

**Comment by yudistrange** [comment]
Thanks Ruben!

**Pull request merged**
