### PR TITLE
Add yandex.png (yandex.svg isn't being found, for some reason)

### PR DESCRIPTION
**Pull request by tsmock**
I thought that the svg was working (I initially had exported a png for yandex, and then removed it to make certain the svg was working. I did not run `ant clean`.).

Signed-off-by: Taylor Smock <taylor.smock@kaartgroup.com>

### CODE REVIEW

**Comment by stoecker** [comment]
Nah. That's the wrong solution. We have a long standing ticket to replace png by svg, so going the other way is not good.

**Comment by tsmock** [comment]
I agree that it is the wrong solution, however it currently breaks plugins under JOSM stable.

Even if it didn't, the supported versions of JOSM for the plugin would run into that bug (r12098+), so until I (or someone else) figures out why svgs aren't being loaded from plugin jars, we cannot bump the required version and only have svgs.

Ideally, we would just swap extensions in `ImageProvider.java` on line 924 so that it reads `extensions = new String[] {".svg", ".png"};` and thus find the svgs before the pngs if both are present. 

That being said, if I remember correctly, when I tested that last night it crashed earlier in the test case ( [L15](https://gitlab.com/smocktaylor/josm_svg_png_test/blob/master/src/org/openstreetmap/josm/plugins/svg_png_test/SvgPngTestPlugin.java#L15) instead of [L17](https://gitlab.com/smocktaylor/josm_svg_png_test/blob/master/src/org/openstreetmap/josm/plugins/svg_png_test/SvgPngTestPlugin.java#L17) )

Edit: For people googling this in the future, the longstanding ticket is [ticket 15240](https://josm.openstreetmap.de/ticket/15240).

**Comment by don-vip** [comment]
The SVG was simply invalid, I fixed it in https://github.com/JOSM/osm-obj-info/releases/tag/v1.3.1

**Comment by tsmock** [comment]
Yep. I spent way to much time trying to figure out what was going on. I didn't think to check the validity of the svg since I had saved it from InkScape.

**Comment by don-vip** [comment]
If you didn't corrupt the SVG file manually it's probably worth reporting the issue to Inkscape. It shouldn't produce garbage like this.

**Comment by tsmock** [comment]
I can't reproduce it, so I don't know if it was something else I did (maybe some odd race condition where the file had been touched, `git stash` had a version and was applying it, and Inkscape was writing to the file).

I'll still file a bug report with them, since Inkscape should at least warn that the svg is malformed.

**Pull request closed without merging**
